# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build, Run tests
      run: |
        swift build -c release --target zyy-reactions --static-swift-stdlib
        ls $GITHUB_WORKSPACE/.build/
        ls $GITHUB_WORKSPACE/.build/release/
        mv $GITHUB_WORKSPACE/.build/release/zyy* $GITHUB_WORKSPACE/
        tar -czvf zyy-reactions-linux-amd64.tar.gz zyy*

    - name: Create a Release
      uses: softprops/action-gh-release@v1
      with:
        files: zyy-reactions-linux-amd64.tar.gz
